<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>scopeName</key>
    <string>text.cyclone</string>
        
	<key>fileTypes</key>
	<array>
		<string>cyclone</string>
	</array>
    
	<key>name</key>
	<string>cyclone file</string>
    
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(start|final|const|always|some|one)\b</string>
			<key>name</key>
			<string>entity.name.tag.cyclone</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(-)?[0-9.]+\b</string>
			<key>name</key>
			<string>constant.numeric.cyclone</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false)\b</string>
			<key>name</key>
			<string>constant.language.cyclone</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\$</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line.cyclone</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\/\/</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line.cyclone</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*\/\*</string>
			<key>end</key>
			<string>\*\/</string>
			<key>name</key>
			<string>comment.block.cyclone</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\"[^\"]*\"</string>
			<key>name</key>
			<string>string.cyclone</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(->|<->)</string>
			<key>name</key>
			<string>string.cyclone.type</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(abstract|at|bool|char|enum|final|int|label|record|let|normal|fresh|on|prev|real|start|string|where|with|initial)\b</string>
			<key>name</key>
			<string>keyword.cyclone.other</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(check|for|enumerate|reach|each|stop|via|upto)\b</string>
			<key>name</key>
			<string>keyword.cyclone.operator</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(assert|condition|goal|in)\b</string>
			<key>name</key>
			<string>keyword.cyclone.condition</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\binvariant\b</string>
			<key>name</key>
			<string>keyword.cyclone.operator</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(graph|machine|node|state|trans|transition|edge|record|function|return)\b</string>
			<key>name</key>
			<string>keyword.cyclone.invariant</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(<<|>>|&&|\|\||!|\^\|\=\>)</string>
			<key>name</key>
			<string>keyword.cyclone.operator.logical</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(<\=|>\=|\=\=|<|>|\!\=)</string>
			<key>name</key>
			<string>keyword.cyclone.operator.comparison</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(<\=|>\=|\=\=|<|>|\!\=)</string>
			<key>name</key>
			<string>keyword.cyclone.operator.comparison</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\=</string>
			<key>name</key>
			<string>keyword.cyclone.operator.assignment</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(\^|>>|<<|_)\b</string>
			<key>name</key>
			<string>keyword.cyclone.operator.bitwise</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\+\+|--)</string>
			<key>name</key>
			<string>keyword.cyclone.operator.arithmetic</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\+|\-|/|\*)</string>
			<key>name</key>
			<string>keyword.cyclone.operator.arithmetic</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\+\=|-\=|\*\=|/\=)</string>
			<key>name</key>
			<string>keyword.cyclone.operator.assignment.augmented</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[[:alpha:]_][[:alnum:]_]*\b</string>
			<key>name</key>
			<string>variable.cyclone.identifier</string>
		</dict>
	</array>
</dict>
</plist>